# java.properties

# Maven projesinde derlenmiş test sınıflarının yeri
gauge_custom_build_path = target/test-classes

# Maven dependency'leri `mvn test-compile` ile buraya kopyalanır.
gauge_additional_libs = target/gauge-libs/*

